INSERT INTO series (title, author_id, subgenre_id) VALUES ("Harry Potter", 1, 1)
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Lord of the Rings", )

INSERT INTO books (title, year, series_id) VALUES ()
INSERT INTO books (title, year, series_id) VALUES ()
INSERT INTO books (title, year, series_id) VALUES ()
INSERT INTO books (title, year, series_id) VALUES ()
INSERT INTO books (title, year, series_id) VALUES ()
INSERT INTO books (title, year, series_id) VALUES ()

INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ()

INSERT INTO subgenres (name) VALUES ()
INSERT INTO subgenres (name) VALUES ()

INSERT INTO authors (name) VALUES ()
INSERT INTO authors (name) VALUES ()

INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
INSERT INTO character_books (book_id, character_id) VALUES ()
